version: "3.9"
   
services:
  web:
    container_name: sisacad-app
    image: sisacad-app
    build:
      context: .
      #dockerfile: .docker/node.development.dockerfile
    volumes:
      - .:/var/www/sisacad-app
      - /var/www/sisacad-app/node_modules
    environment:
      - npm_config_unsafe_perm=true
    ports:
      - "8080:8080"


